export const QuirkymalTuning = {
	Alligator: {
		Animation: "AlligatorAnimation",
		Conditions: [
			{ RequiredAmount: 1000, Type: "Price" },
			{ RequiredTrait: "ReptileFan", Type: "Trait" },
		],
		Effects: [{ Amount: 20, Mood: "Alert", Type: "MoodChange" }],
		FunFact: "Alligator secretly loves sunbathing but always forgets sunscreen.",
		Name: "Alligator",
		Type: "Quirkymal",
	},
	Alpaca: {
		Animation: "AlpacaAnimation",
		Conditions: [
			{ RequiredAmount: 800, Type: "Price" },
			{ RequiredTrait: "FarmLover", Type: "Trait" },
		],
		Effects: [{ Amount: 15, Mood: "Calm", Type: "MoodChange" }],
		FunFact: "Alpaca insists on brushing its fur exactly 100 times a day.",
		Name: "Alpaca",
		Type: "Quirkymal",
	},
	Antelope: {
		Animation: "AntelopeAnimation",
		Conditions: [
			{ RequiredAmount: 900, Type: "Price" },
			{ RequiredTrait: "WildlifeFan", Type: "Trait" },
		],
		Effects: [{ Amount: 18, Mood: "Graceful", Type: "MoodChange" }],
		FunFact: "Antelope has never tripped once, but fears stepping on a banana peel.",
		Name: "Antelope",
		Type: "Quirkymal",
	},
	ArcticFox: {
		Animation: "ArcticFoxAnimation",
		Conditions: [
			{ RequiredAmount: 1200, Type: "Price" },
			{ RequiredTrait: "WildlifeFan", Type: "Trait" },
		],
		Effects: [{ Amount: 20, Mood: "Cunning", Type: "MoodChange" }],
		FunFact: "Arctic Fox loves snowball fights, but always hides behind a tree.",
		Name: "ArcticFox",
		Type: "Quirkymal",
	},
	Armadillo: {
		Animation: "ArmadilloAnimation",
		Conditions: [
			{ RequiredAmount: 700, Type: "Price" },
			{ RequiredTrait: "ReptileFan", Type: "Trait" },
		],
		Effects: [{ Amount: 15, Mood: "Protective", Type: "MoodChange" }],
		FunFact: "Armadillo has an irrational fear of marbles rolling too fast.",
		Name: "Armadillo",
		Type: "Quirkymal",
	},
	Arowana: {
		Animation: "ArowanaAnimation",
		Conditions: [
			{ RequiredAmount: 1100, Type: "Price" },
			{ RequiredTrait: "AquaticFan", Type: "Trait" },
		],
		Effects: [{ Amount: 17, Mood: "Serene", Type: "MoodChange" }],
		FunFact: "Arowana loves floating upside down when no one is watching.",
		Name: "Arowana",
		Type: "Quirkymal",
	},
	Baboon: {
		Animation: "BaboonAnimation",
		Conditions: [
			{ RequiredAmount: 950, Type: "Price" },
			{ RequiredTrait: "PrimateLover", Type: "Trait" },
		],
		Effects: [{ Amount: 16, Mood: "Playful", Type: "MoodChange" }],
		FunFact: "Baboon is a champion at hide and seek but always giggles when found.",
		Name: "Baboon",
		Type: "Quirkymal",
	},
	Badger: {
		Animation: "BadgerAnimation",
		Conditions: [
			{ RequiredAmount: 850, Type: "Price" },
			{ RequiredTrait: "WildlifeFan", Type: "Trait" },
		],
		Effects: [{ Amount: 14, Mood: "Curious", Type: "MoodChange" }],
		FunFact: "Badger can dig tunnels faster than it can eat its breakfast.",
		Name: "Badger",
		Type: "Quirkymal",
	},
	Bandicoot: {
		Animation: "BandicootAnimation",
		Conditions: [
			{ RequiredAmount: 800, Type: "Price" },
			{ RequiredTrait: "WildlifeFan", Type: "Trait" },
		],
		Effects: [{ Amount: 15, Mood: "Energetic", Type: "MoodChange" }],
		FunFact: "Bandicoot has a collection of bottle caps from all over the forest.",
		Name: "Bandicoot",
		Type: "Quirkymal",
	},
	Bass: {
		Animation: "BassAnimation",
		Conditions: [
			{ RequiredAmount: 600, Type: "Price" },
			{ RequiredTrait: "AquaticFan", Type: "Trait" },
		],
		Effects: [{ Amount: 12, Mood: "Relaxed", Type: "MoodChange" }],
		FunFact: "Bass loves swimming against the current just for the fun of it.",
		Name: "Bass",
		Type: "Quirkymal",
	},
	Bat: {
		Animation: "BatAnimation",
		Conditions: [
			{ RequiredAmount: 500, Type: "Price" },
			{ RequiredTrait: "NightCreatureLover", Type: "Trait" },
		],
		Effects: [{ Amount: 10, Mood: "Mysterious", Type: "MoodChange" }],
		FunFact: "Bat never gets lost, even in the darkest caves.",
		Name: "Bat",
		Type: "Quirkymal",
	},
	Bear: {
		Animation: "BearAnimation",
		Conditions: [
			{ RequiredAmount: 1500, Type: "Price" },
			{ RequiredTrait: "WildlifeFan", Type: "Trait" },
		],
		Effects: [{ Amount: 20, Mood: "Strong", Type: "MoodChange" }],
		FunFact: "Bear snores so loudly, it echoes through the entire forest.",
		Name: "Bear",
		Type: "Quirkymal",
	},
	Beaver: {
		Animation: "BeaverAnimation",
		Conditions: [
			{ RequiredAmount: 700, Type: "Price" },
			{ RequiredTrait: "FarmLover", Type: "Trait" },
		],
		Effects: [{ Amount: 14, Mood: "Diligent", Type: "MoodChange" }],
		FunFact: "Beaver once built a dam that accidentally redirected the river.",
		Name: "Beaver",
		Type: "Quirkymal",
	},
	Beluga: {
		Animation: "BelugaAnimation",
		Conditions: [
			{ RequiredAmount: 1300, Type: "Price" },
			{ RequiredTrait: "AquaticFan", Type: "Trait" },
		],
		Effects: [{ Amount: 18, Mood: "Joyful", Type: "MoodChange" }],
		FunFact: "Beluga loves singing underwater and puts on a concert every evening.",
		Name: "Beluga",
		Type: "Quirkymal",
	},
	Bighorn: {
		Animation: "BighornAnimation",
		Conditions: [
			{ RequiredAmount: 1600, Type: "Price" },
			{ RequiredTrait: "BigHornLover", Type: "Trait" },
		],
		Effects: [{ Amount: 22, Mood: "Majestic", Type: "MoodChange" }],
		FunFact: "Bighorn enjoys balancing on the thinnest mountain ledges just for kicks.",
		Name: "Bighorn",
		Type: "Quirkymal",
	},
	Bison: {
		Animation: "BisonAnimation",
		Conditions: [
			{ RequiredAmount: 1400, Type: "Price" },
			{ RequiredTrait: "SavannaLover", Type: "Trait" },
		],
		Effects: [{ Amount: 20, Mood: "Strong", Type: "MoodChange" }],
		FunFact: "Bison runs the fastest in the herd, but only when no one's looking.",
		Name: "Bison",
		Type: "Quirkymal",
	},
	Buffalo: {
		Animation: "BuffaloAnimation",
		Conditions: [
			{ RequiredAmount: 1500, Type: "Price" },
			{ RequiredTrait: "SavannaLover", Type: "Trait" },
		],
		Effects: [{ Amount: 25, Mood: "Powerful", Type: "MoodChange" }],
		FunFact: "Buffalo loves rolling in the mud after a good run to cool down.",
		Name: "Buffalo",
		Type: "Quirkymal",
	},
	Bull: {
		Animation: "BullAnimation",
		Conditions: [
			{ RequiredAmount: 800, Type: "Price" },
			{ RequiredTrait: "FarmLover", Type: "Trait" },
		],
		Effects: [{ Amount: 18, Mood: "Confident", Type: "MoodChange" }],
		FunFact: "Bull loves practicing its horn tossing skills with hay bales.",
		Name: "Bull",
		Type: "Quirkymal",
	},
	Camel: {
		Animation: "CamelAnimation",
		Conditions: [
			{ RequiredAmount: 900, Type: "Price" },
			{ RequiredTrait: "DesertLover", Type: "Trait" },
		],
		Effects: [{ Amount: 16, Mood: "Resilient", Type: "MoodChange" }],
		FunFact: "Camel can drink up to 50 gallons of water but only complains if it's too cold.",
		Name: "Camel",
		Type: "Quirkymal",
	},
	Capybara: {
		Animation: "CapybaraAnimation",
		Conditions: [
			{ RequiredAmount: 850, Type: "Price" },
			{ RequiredTrait: "AquaticFan", Type: "Trait" },
		],
		Effects: [{ Amount: 14, Mood: "Relaxed", Type: "MoodChange" }],
		FunFact: "Capybara enjoys sitting still for hours, watching the river flow by.",
		Name: "Capybara",
		Type: "Quirkymal",
	},
	Cardinal: {
		Animation: "CardinalAnimation",
		Conditions: [
			{ RequiredAmount: 500, Type: "Price" },
			{ RequiredTrait: "BirdLover", Type: "Trait" },
		],
		Effects: [{ Amount: 10, Mood: "Happy", Type: "MoodChange" }],
		FunFact: "Cardinal wakes up before sunrise just to serenade the forest.",
		Name: "Cardinal",
		Type: "Quirkymal",
	},
	Carp: {
		Animation: "CarpAnimation",
		Conditions: [
			{ RequiredAmount: 450, Type: "Price" },
			{ RequiredTrait: "AquaticFan", Type: "Trait" },
		],
		Effects: [{ Amount: 8, Mood: "Relaxed", Type: "MoodChange" }],
		FunFact: "Carp loves swimming in circles when it gets bored.",
		Name: "Carp",
		Type: "Quirkymal",
	},
	Cat: {
		Animation: "CatAnimation",
		Conditions: [
			{ RequiredAmount: 700, Type: "Price" },
			{ RequiredTrait: "CatLover", Type: "Trait" },
		],
		Effects: [{ Amount: 15, Mood: "Comforted", Type: "MoodChange" }],
		FunFact: "Cat believes every piece of furniture was made for napping.",
		Name: "Cat",
		Type: "Quirkymal",
	},
	Catfish: {
		Animation: "CatfishAnimation",
		Conditions: [
			{ RequiredAmount: 500, Type: "Price" },
			{ RequiredTrait: "AquaticFan", Type: "Trait" },
		],
		Effects: [{ Amount: 9, Mood: "Curious", Type: "MoodChange" }],
		FunFact: "Catfish prefers to swim backward just to show off.",
		Name: "Catfish",
		Type: "Quirkymal",
	},
	Cerberus: {
		Animation: "CerberusAnimation",
		Conditions: [
			{ RequiredAmount: 5000, Type: "Price" },
			{ RequiredTrait: "MythicLover", Type: "Trait" },
		],
		Effects: [{ Amount: 25, Mood: "Powerful", Type: "MoodChange" }],
		FunFact: "Cerberus can never decide which head gets to bark first.",
		Name: "Cerberus",
		Type: "Quirkymal",
	},
	Chameleon: {
		Animation: "ChameleonAnimation",
		Conditions: [
			{ RequiredAmount: 600, Type: "Price" },
			{ RequiredTrait: "ReptileFan", Type: "Trait" },
		],
		Effects: [{ Amount: 12, Mood: "Intrigued", Type: "MoodChange" }],
		FunFact: "Chameleon changes colors based on its favorite song of the day.",
		Name: "Chameleon",
		Type: "Quirkymal",
	},
	Cheetah: {
		Animation: "CheetahAnimation",
		Conditions: [
			{ RequiredAmount: 1500, Type: "Price" },
			{ RequiredTrait: "Speedster", Type: "Trait" },
		],
		Effects: [{ Amount: 20, Mood: "Excited", Type: "MoodChange" }],
		FunFact: "Cheetah is the fastest runner but loves lounging under a shady tree.",
		Name: "Cheetah",
		Type: "Quirkymal",
	},
	Chick: {
		Animation: "ChickAnimation",
		Conditions: [
			{ RequiredAmount: 300, Type: "Price" },
			{ RequiredTrait: "FarmLover", Type: "Trait" },
		],
		Effects: [{ Amount: 8, Mood: "Nurturing", Type: "MoodChange" }],
		FunFact: "Chick loves pecking at every breadcrumb it finds, even if it's full.",
		Name: "Chick",
		Type: "Quirkymal",
	},
	Chimp: {
		Animation: "ChimpAnimation",
		Conditions: [
			{ RequiredAmount: 1000, Type: "Price" },
			{ RequiredTrait: "PrimateLover", Type: "Trait" },
		],
		Effects: [{ Amount: 15, Mood: "Playful", Type: "MoodChange" }],
		FunFact: "Chimp loves playing pranks on the other animals but always apologizes with a banana.",
		Name: "Chimp",
		Type: "Quirkymal",
	},
	ChineseDragon: {
		Animation: "ChineseDragonAnimation",
		Conditions: [
			{ RequiredAmount: 4000, Type: "Price" },
			{ RequiredTrait: "MythicLover", Type: "Trait" },
		],
		Effects: [{ Amount: 30, Mood: "Majestic", Type: "MoodChange" }],
		FunFact: "Chinese Dragon enjoys flying in spirals and creating smoke rings with its breath.",
		Name: "ChineseDragon",
		Type: "Quirkymal",
	},
	Chipmunk: {
		Animation: "ChipmunkAnimation",
		Conditions: [
			{ RequiredAmount: 600, Type: "Price" },
			{ RequiredTrait: "RodentFan", Type: "Trait" },
		],
		Effects: [{ Amount: 10, Mood: "Cheerful", Type: "MoodChange" }],
		FunFact: "Chipmunk can store over 100 acorns in its cheeks but always loses track of them.",
		Name: "Chipmunk",
		Type: "Quirkymal",
	},
	Clownfish: {
		Animation: "ClownfishAnimation",
		Conditions: [
			{ RequiredAmount: 400, Type: "Price" },
			{ RequiredTrait: "AquaticFan", Type: "Trait" },
		],
		Effects: [{ Amount: 7, Mood: "Amused", Type: "MoodChange" }],
		FunFact: "Clownfish loves playing hide and seek in coral, and it's always the best hider.",
		Name: "Clownfish",
		Type: "Quirkymal",
	},
	Cobra: {
		Animation: "CobraAnimation",
		Conditions: [
			{ RequiredAmount: 900, Type: "Price" },
			{ RequiredTrait: "ReptileFan", Type: "Trait" },
		],
		Effects: [{ Amount: 14, Mood: "Alert", Type: "MoodChange" }],
		FunFact: "Cobra likes to practice its hood display in front of reflective surfaces.",
		Name: "Cobra",
		Type: "Quirkymal",
	},
	Cougar: {
		Animation: "CougarAnimation",
		Conditions: [
			{ RequiredAmount: 1200, Type: "Price" },
			{ RequiredTrait: "BigCatLover", Type: "Trait" },
		],
		Effects: [{ Amount: 18, Mood: "Confident", Type: "MoodChange" }],
		FunFact: "Cougar loves scaling rocky cliffs but never without a stretch first.",
		Name: "Cougar",
		Type: "Quirkymal",
	},
	Cow: {
		Animation: "CowAnimation",
		Conditions: [
			{ RequiredAmount: 800, Type: "Price" },
			{ RequiredTrait: "FarmLover", Type: "Trait" },
		],
		Effects: [{ Amount: 12, Mood: "Content", Type: "MoodChange" }],
		FunFact: "Cow loves chewing grass and dreams of visiting new fields every day.",
		Name: "Cow",
		Type: "Quirkymal",
	},
	Coyote: {
		Animation: "CoyoteAnimation",
		Conditions: [
			{ RequiredAmount: 900, Type: "Price" },
			{ RequiredTrait: "WildlifeFan", Type: "Trait" },
		],
		Effects: [{ Amount: 14, Mood: "Curious", Type: "MoodChange" }],
		FunFact: "Coyote howls at the moon not because it’s lonely, but because it likes the echo.",
		Name: "Coyote",
		Type: "Quirkymal",
	},
	Crab: {
		Animation: "CrabAnimation",
		Conditions: [
			{ RequiredAmount: 400, Type: "Price" },
			{ RequiredTrait: "AquaticFan", Type: "Trait" },
		],
		Effects: [{ Amount: 7, Mood: "Entertained", Type: "MoodChange" }],
		FunFact: "Crab loves to dance sideways across the beach when no one's watching.",
		Name: "Crab",
		Type: "Quirkymal",
	},
	Crocodile: {
		Animation: "CrocodileAnimation",
		Conditions: [
			{ RequiredAmount: 1300, Type: "Price" },
			{ RequiredTrait: "ReptileFan", Type: "Trait" },
		],
		Effects: [{ Amount: 20, Mood: "Powerful", Type: "MoodChange" }],
		FunFact: "Crocodile could swim for hours but secretly loves napping on the shore.",
		Name: "Crocodile",
		Type: "Quirkymal",
	},
	Crow: {
		Animation: "CrowAnimation",
		Conditions: [
			{ RequiredAmount: 600, Type: "Price" },
			{ RequiredTrait: "BirdLover", Type: "Trait" },
		],
		Effects: [{ Amount: 10, Mood: "Mysterious", Type: "MoodChange" }],
		FunFact: "Crow has a secret stash of shiny trinkets hidden in the tallest tree.",
		Name: "Crow",
		Type: "Quirkymal",
	},
	Deer: {
		Animation: "DeerAnimation",
		Conditions: [
			{ RequiredAmount: 1000, Type: "Price" },
			{ RequiredTrait: "ForestLover", Type: "Trait" },
		],
		Effects: [{ Amount: 15, Mood: "Peaceful", Type: "MoodChange" }],
		FunFact: "Deer is incredibly graceful but has a soft spot for crunchy leaves.",
		Name: "Deer",
		Type: "Quirkymal",
	},
	Dingo: {
		Animation: "DingoAnimation",
		Conditions: [
			{ RequiredAmount: 1100, Type: "Price" },
			{ RequiredTrait: "WildlifeFan", Type: "Trait" },
		],
		Effects: [{ Amount: 17, Mood: "Adventurous", Type: "MoodChange" }],
		FunFact: "Dingo loves to howl with the wind, making it seem like part of the breeze.",
		Name: "Dingo",
		Type: "Quirkymal",
	},
	Dog: {
		Animation: "DogAnimation",
		Conditions: [
			{ RequiredAmount: 900, Type: "Price" },
			{ RequiredTrait: "DogLover", Type: "Trait" },
		],
		Effects: [{ Amount: 14, Mood: "Loyal", Type: "MoodChange" }],
		FunFact: "Dog wags its tail so fast it once knocked over a stack of books.",
		Name: "Dog",
		Type: "Quirkymal",
	},
	Dolphin: {
		Animation: "DolphinAnimation",
		Conditions: [
			{ RequiredAmount: 1300, Type: "Price" },
			{ RequiredTrait: "AquaticFan", Type: "Trait" },
		],
		Effects: [{ Amount: 20, Mood: "Joyful", Type: "MoodChange" }],
		FunFact: "Dolphin loves to leap out of the water, performing tricks for the fish.",
		Name: "Dolphin",
		Type: "Quirkymal",
	},
	Donkey: {
		Animation: "DonkeyAnimation",
		Conditions: [
			{ RequiredAmount: 700, Type: "Price" },
			{ RequiredTrait: "FarmLover", Type: "Trait" },
		],
		Effects: [{ Amount: 12, Mood: "Stubborn", Type: "MoodChange" }],
		FunFact: "Donkey can carry heavy loads but loves taking breaks to eat wildflowers.",
		Name: "Donkey",
		Type: "Quirkymal",
	},
	Dove: {
		Animation: "DoveAnimation",
		Conditions: [
			{ RequiredAmount: 500, Type: "Price" },
			{ RequiredTrait: "BirdLover", Type: "Trait" },
		],
		Effects: [{ Amount: 10, Mood: "Calm", Type: "MoodChange" }],
		FunFact: "Dove coos the softest lullabies but dreams of singing in a rock band.",
		Name: "Dove",
		Type: "Quirkymal",
	},
	Dragon: {
		Animation: "DragonAnimation",
		Conditions: [
			{ RequiredAmount: 10000, Type: "Price" },
			{ RequiredTrait: "MythicLover", Type: "Trait" },
		],
		Effects: [{ Amount: 25, Mood: "Powerful", Type: "MoodChange" }],
		FunFact: "Dragon loves lighting campfires with its breath and roasting marshmallows.",
		Name: "Dragon",
		Type: "Quirkymal",
	},
	Duck: {
		Animation: "DuckAnimation",
		Conditions: [
			{ RequiredAmount: 600, Type: "Price" },
			{ RequiredTrait: "FarmLover", Type: "Trait" },
		],
		Effects: [{ Amount: 12, Mood: "Playful", Type: "MoodChange" }],
		FunFact: "Duck loves splashing in puddles even when there's no one else around.",
		Name: "Duck",
		Type: "Quirkymal",
	},
	Eagle: {
		Animation: "EagleAnimation",
		Conditions: [
			{ RequiredAmount: 1500, Type: "Price" },
			{ RequiredTrait: "BirdLover", Type: "Trait" },
		],
		Effects: [{ Amount: 20, Mood: "Free", Type: "MoodChange" }],
		FunFact: "Eagle loves soaring to the highest peaks but never misses a chance to swoop low.",
		Name: "Eagle",
		Type: "Quirkymal",
	},
	Echidna: {
		Animation: "EchidnaAnimation",
		Conditions: [
			{ RequiredAmount: 800, Type: "Price" },
			{ RequiredTrait: "WildlifeFan", Type: "Trait" },
		],
		Effects: [{ Amount: 12, Mood: "Curious", Type: "MoodChange" }],
		FunFact: "Echidna has the longest tongue in the forest but only uses it to taste honey.",
		Name: "Echidna",
		Type: "Quirkymal",
	},
	Elephant: {
		Animation: "ElephantAnimation",
		Conditions: [
			{ RequiredAmount: 2000, Type: "Price" },
			{ RequiredTrait: "SavannaLover", Type: "Trait" },
		],
		Effects: [{ Amount: 25, Mood: "Gentle", Type: "MoodChange" }],
		FunFact: "Elephant can remember everything but often forgets where it left its favorite leaf.",
		Name: "Elephant",
		Type: "Quirkymal",
	},
	Emu: {
		Animation: "EmuAnimation",
		Conditions: [
			{ RequiredAmount: 900, Type: "Price" },
			{ RequiredTrait: "BirdLover", Type: "Trait" },
		],
		Effects: [{ Amount: 14, Mood: "Curious", Type: "MoodChange" }],
		FunFact: "Emu runs in zigzags not to escape but just because it’s fun.",
		Name: "Emu",
		Type: "Quirkymal",
	},
	FennecFox: {
		Animation: "FennecFoxAnimation",
		Conditions: [
			{ RequiredAmount: 1200, Type: "Price" },
			{ RequiredTrait: "WildlifeFan", Type: "Trait" },
		],
		Effects: [{ Amount: 18, Mood: "Cute", Type: "MoodChange" }],
		FunFact: "Fennec Fox's ears twitch when it's excited, which is all the time.",
		Name: "FennecFox",
		Type: "Quirkymal",
	},
	Ferret: {
		Animation: "FerretAnimation",
		Conditions: [
			{ RequiredAmount: 800, Type: "Price" },
			{ RequiredTrait: "RodentFan", Type: "Trait" },
		],
		Effects: [{ Amount: 12, Mood: "Playful", Type: "MoodChange" }],
		FunFact: "Ferret loves squeezing into small spaces but always forgets how to get out.",
		Name: "Ferret",
		Type: "Quirkymal",
	},
	Flamingo: {
		Animation: "FlamingoAnimation",
		Conditions: [
			{ RequiredAmount: 1400, Type: "Price" },
			{ RequiredTrait: "BirdLover", Type: "Trait" },
		],
		Effects: [{ Amount: 20, Mood: "Graceful", Type: "MoodChange" }],
		FunFact: "Flamingo balances on one leg not for comfort, but for the style points.",
		Name: "Flamingo",
		Type: "Quirkymal",
	},
	FlyingFox: {
		Animation: "FlyingFoxAnimation",
		Conditions: [
			{ RequiredAmount: 1000, Type: "Price" },
			{ RequiredTrait: "WildlifeFan", Type: "Trait" },
		],
		Effects: [{ Amount: 15, Mood: "Mysterious", Type: "MoodChange" }],
		FunFact: "Flying Fox loves hanging upside down to get a different perspective.",
		Name: "FlyingFox",
		Type: "Quirkymal",
	},
	Fox: {
		Animation: "FoxAnimation",
		Conditions: [
			{ RequiredAmount: 1000, Type: "Price" },
			{ RequiredTrait: "WildlifeFan", Type: "Trait" },
		],
		Effects: [{ Amount: 15, Mood: "Cunning", Type: "MoodChange" }],
		FunFact: "Fox loves playing tricks but always leaves a hint behind for fun.",
		Name: "Fox",
		Type: "Quirkymal",
	},
	Frog: {
		Animation: "FrogAnimation",
		Conditions: [
			{ RequiredAmount: 600, Type: "Price" },
			{ RequiredTrait: "AmphibianFan", Type: "Trait" },
		],
		Effects: [{ Amount: 10, Mood: "Playful", Type: "MoodChange" }],
		FunFact: "Frog has the biggest splash when it jumps into the pond.",
		Name: "Frog",
		Type: "Quirkymal",
	},
	Gaur: {
		Animation: "GaurAnimation",
		Conditions: [
			{ RequiredAmount: 1600, Type: "Price" },
			{ RequiredTrait: "WildlifeFan", Type: "Trait" },
		],
		Effects: [{ Amount: 22, Mood: "Strong", Type: "MoodChange" }],
		FunFact: "Gaur loves munching on grass, but only if it’s freshly watered.",
		Name: "Gaur",
		Type: "Quirkymal",
	},
	Gazelle: {
		Animation: "GazelleAnimation",
		Conditions: [
			{ RequiredAmount: 1200, Type: "Price" },
			{ RequiredTrait: "SavannaLover", Type: "Trait" },
		],
		Effects: [{ Amount: 18, Mood: "Graceful", Type: "MoodChange" }],
		FunFact: "Gazelle can leap over anything, but it prefers hopping over small rocks.",
		Name: "Gazelle",
		Type: "Quirkymal",
	},
	Gecko: {
		Animation: "GeckoAnimation",
		Conditions: [
			{ RequiredAmount: 700, Type: "Price" },
			{ RequiredTrait: "ReptileFan", Type: "Trait" },
		],
		Effects: [{ Amount: 12, Mood: "Fascinated", Type: "MoodChange" }],
		FunFact: "Gecko loves sticking to walls, but always leaves tiny footprints behind.",
		Name: "Gecko",
		Type: "Quirkymal",
	},
	Gemsbok: {
		Animation: "GemsbokAnimation",
		Conditions: [
			{ RequiredAmount: 1400, Type: "Price" },
			{ RequiredTrait: "WildlifeFan", Type: "Trait" },
		],
		Effects: [{ Amount: 20, Mood: "Admiring", Type: "MoodChange" }],
		FunFact: "Gemsbok's horns are so sharp it can carve shapes into the sand.",
		Name: "Gemsbok",
		Type: "Quirkymal",
	},
	GilaMonster: {
		Animation: "GilaMonsterAnimation",
		Conditions: [
			{ RequiredAmount: 1100, Type: "Price" },
			{ RequiredTrait: "ReptileFan", Type: "Trait" },
		],
		Effects: [{ Amount: 17, Mood: "Alert", Type: "MoodChange" }],
		FunFact: "Gila Monster loves sunbathing on rocks but never skips the shade.",
		Name: "GilaMonster",
		Type: "Quirkymal",
	},
	Giraffe: {
		Animation: "GiraffeAnimation",
		Conditions: [
			{ RequiredAmount: 1800, Type: "Price" },
			{ RequiredTrait: "SavannaLover", Type: "Trait" },
		],
		Effects: [{ Amount: 22, Mood: "Amazed", Type: "MoodChange" }],
		FunFact: "Giraffe can see for miles, but it always looks down to check on the ants.",
		Name: "Giraffe",
		Type: "Quirkymal",
	},
	Goat: {
		Animation: "GoatAnimation",
		Conditions: [
			{ RequiredAmount: 800, Type: "Price" },
			{ RequiredTrait: "FarmLover", Type: "Trait" },
		],
		Effects: [{ Amount: 12, Mood: "Mischievous", Type: "MoodChange" }],
		FunFact: "Goat loves climbing trees just to surprise the birds.",
		Name: "Goat",
		Type: "Quirkymal",
	},
	GoldenEagle: {
		Animation: "GoldenEagleAnimation",
		Conditions: [
			{ RequiredAmount: 1700, Type: "Price" },
			{ RequiredTrait: "BirdLover", Type: "Trait" },
		],
		Effects: [{ Amount: 22, Mood: "Majestic", Type: "MoodChange" }],
		FunFact: "Golden Eagle once flew from sunrise to sunset just to see the colors change.",
		Name: "GoldenEagle",
		Type: "Quirkymal",
	},
	Goldfish: {
		Animation: "GoldfishAnimation",
		Conditions: [
			{ RequiredAmount: 300, Type: "Price" },
			{ RequiredTrait: "AquaticFan", Type: "Trait" },
		],
		Effects: [{ Amount: 8, Mood: "Tranquil", Type: "MoodChange" }],
		FunFact: "Goldfish blows bubbles when it’s happy, and the pond is always bubbly.",
		Name: "Goldfish",
		Type: "Quirkymal",
	},
	Goose: {
		Animation: "GooseAnimation",
		Conditions: [
			{ RequiredAmount: 700, Type: "Price" },
			{ RequiredTrait: "FarmLover", Type: "Trait" },
		],
		Effects: [{ Amount: 12, Mood: "Playful", Type: "MoodChange" }],
		FunFact: "Goose loves honking in the middle of the night just to stir things up.",
		Name: "Goose",
		Type: "Quirkymal",
	},
	Gorilla: {
		Animation: "GorillaAnimation",
		Conditions: [
			{ RequiredAmount: 2200, Type: "Price" },
			{ RequiredTrait: "PrimateLover", Type: "Trait" },
		],
		Effects: [{ Amount: 25, Mood: "Powerful", Type: "MoodChange" }],
		FunFact: "Gorilla enjoys beating its chest in rhythm to the raindrops.",
		Name: "Gorilla",
		Type: "Quirkymal",
	},
	Hamster: {
		Animation: "HamsterAnimation",
		Conditions: [
			{ RequiredAmount: 500, Type: "Price" },
			{ RequiredTrait: "RodentFan", Type: "Trait" },
		],
		Effects: [{ Amount: 10, Mood: "Adorable", Type: "MoodChange" }],
		FunFact: "Hamster loves running in its wheel but often takes breaks to snack on sunflower seeds.",
		Name: "Hamster",
		Type: "Quirkymal",
	},
	Hare: {
		Animation: "HareAnimation",
		Conditions: [
			{ RequiredAmount: 600, Type: "Price" },
			{ RequiredTrait: "WildlifeFan", Type: "Trait" },
		],
		Effects: [{ Amount: 12, Mood: "Energetic", Type: "MoodChange" }],
		FunFact: "Hare races everyone but loves slowing down to smell the flowers.",
		Name: "Hare",
		Type: "Quirkymal",
	},
	Hedgehog: {
		Animation: "HedgehogAnimation",
		Conditions: [
			{ RequiredAmount: 800, Type: "Price" },
			{ RequiredTrait: "RodentFan", Type: "Trait" },
		],
		Effects: [{ Amount: 12, Mood: "Curious", Type: "MoodChange" }],
		FunFact: "Hedgehog curls into a ball every time it hears a joke.",
		Name: "Hedgehog",
		Type: "Quirkymal",
	},
	Hen: {
		Animation: "HenAnimation",
		Conditions: [
			{ RequiredAmount: 500, Type: "Price" },
			{ RequiredTrait: "FarmLover", Type: "Trait" },
		],
		Effects: [{ Amount: 10, Mood: "Nurturing", Type: "MoodChange" }],
		FunFact: "Hen loves waking up early to collect the finest grains for breakfast.",
		Name: "Hen",
		Type: "Quirkymal",
	},
	Herring: {
		Animation: "HerringAnimation",
		Conditions: [
			{ RequiredAmount: 300, Type: "Price" },
			{ RequiredTrait: "AquaticFan", Type: "Trait" },
		],
		Effects: [{ Amount: 8, Mood: "Content", Type: "MoodChange" }],
		FunFact: "Herring swims in perfect harmony with the school but loves to splash out solo.",
		Name: "Herring",
		Type: "Quirkymal",
	},
	Hippo: {
		Animation: "HippoAnimation",
		Conditions: [
			{ RequiredAmount: 1800, Type: "Price" },
			{ RequiredTrait: "SavannaLover", Type: "Trait" },
		],
		Effects: [{ Amount: 22, Mood: "Relaxed", Type: "MoodChange" }],
		FunFact: "Hippo spends more time in the water than out but always keeps its head above.",
		Name: "Hippo",
		Type: "Quirkymal",
	},
	Hog: {
		Animation: "HogAnimation",
		Conditions: [
			{ RequiredAmount: 900, Type: "Price" },
			{ RequiredTrait: "FarmLover", Type: "Trait" },
		],
		Effects: [{ Amount: 14, Mood: "Mischievous", Type: "MoodChange" }],
		FunFact: "Hog loves rolling in the mud but always takes a bath afterward.",
		Name: "Hog",
		Type: "Quirkymal",
	},
	Hornbill: {
		Animation: "HornbillAnimation",
		Conditions: [
			{ RequiredAmount: 1300, Type: "Price" },
			{ RequiredTrait: "BirdLover", Type: "Trait" },
		],
		Effects: [{ Amount: 18, Mood: "Fascinated", Type: "MoodChange" }],
		FunFact: "Hornbill spends hours polishing its beak to keep it shiny.",
		Name: "Hornbill",
		Type: "Quirkymal",
	},
	HornedLizard: {
		Animation: "HornedLizardAnimation",
		Conditions: [
			{ RequiredAmount: 1000, Type: "Price" },
			{ RequiredTrait: "ReptileFan", Type: "Trait" },
		],
		Effects: [{ Amount: 15, Mood: "Curious", Type: "MoodChange" }],
		FunFact: "Horned Lizard loves hiding in plain sight, always camouflaging perfectly.",
		Name: "HornedLizard",
		Type: "Quirkymal",
	},
	Horse: {
		Animation: "HorseAnimation",
		Conditions: [
			{ RequiredAmount: 1600, Type: "Price" },
			{ RequiredTrait: "FarmLover", Type: "Trait" },
		],
		Effects: [{ Amount: 20, Mood: "Free", Type: "MoodChange" }],
		FunFact: "Horse loves running through open fields but always stops to admire the sunset.",
		Name: "Horse",
		Type: "Quirkymal",
	},
	Husky: {
		Animation: "HuskyAnimation",
		Conditions: [
			{ RequiredAmount: 1000, Type: "Price" },
			{ RequiredTrait: "DogLover", Type: "Trait" },
		],
		Effects: [{ Amount: 15, Mood: "Playful", Type: "MoodChange" }],
		FunFact: "Husky loves pulling sleds through snow but never misses a chance to roll in it.",
		Name: "Husky",
		Type: "Quirkymal",
	},
	Hyena: {
		Animation: "HyenaAnimation",
		Conditions: [
			{ RequiredAmount: 1200, Type: "Price" },
			{ RequiredTrait: "SavannaLover", Type: "Trait" },
		],
		Effects: [{ Amount: 18, Mood: "Mischievous", Type: "MoodChange" }],
		FunFact: "Hyena laughs not because it’s funny, but because it loves the sound of its own voice.",
		Name: "Hyena",
		Type: "Quirkymal",
	},
	// Ibex: {
	// 	Animation: "IbexAnimation",
	// 	Conditions: [
	// 		{ RequiredAmount: 1300, Type: "Price" },
	// 		{ RequiredTrait: "WildlifeFan", Type: "Trait" },
	// 	],
	// 	Effects: [{ Amount: 18, Mood: "Confident", Type: "MoodChange" }],
	// 	FunFact: "Ibex loves standing on the steepest cliffs, daring the wind to push it.",
	// 	Name: "Ibex",
	// 	Type: "Quirkymal",
	// },
	Iguana: {
		Animation: "IguanaAnimation",
		Conditions: [
			{ RequiredAmount: 700, Type: "Price" },
			{ RequiredTrait: "ReptileFan", Type: "Trait" },
		],
		Effects: [{ Amount: 12, Mood: "Relaxed", Type: "MoodChange" }],
		FunFact: "Iguana loves climbing trees to nap in the sun but always finds the shadiest spot.",
		Name: "Iguana",
		Type: "Quirkymal",
	},
	// Impala: {
	// 	Animation: "ImpalaAnimation",
	// 	Conditions: [
	// 		{ RequiredAmount: 1200, Type: "Price" },
	// 		{ RequiredTrait: "SavannaLover", Type: "Trait" },
	// 	],
	// 	Effects: [{ Amount: 18, Mood: "Graceful", Type: "MoodChange" }],
	// 	FunFact: "Impala loves racing the wind and always wins, but never tells anyone.",
	// 	Name: "Impala",
	// 	Type: "Quirkymal",
	// },
	Inkfish: {
		Animation: "InkfishAnimation",
		Conditions: [
			{ RequiredAmount: 900, Type: "Price" },
			{ RequiredTrait: "AquaticFan", Type: "Trait" },
		],
		Effects: [{ Amount: 14, Mood: "Curious", Type: "MoodChange" }],
		FunFact: "InkFish loves to swim in ink but always cleans up before bedtime.",
		Name: "Inkfish",
		Type: "Quirkymal",
	},
	Jackal: {
		Animation: "JackalAnimation",
		Conditions: [
			{ RequiredAmount: 1000, Type: "Price" },
			{ RequiredTrait: "WildlifeFan", Type: "Trait" },
		],
		Effects: [{ Amount: 15, Mood: "Clever", Type: "MoodChange" }],
		FunFact: "Jackal loves solving puzzles but prefers to leave clues for others to follow.",
		Name: "Jackal",
		Type: "Quirkymal",
	},
	Jackrabbit: {
		Animation: "JackrabbitAnimation",
		Conditions: [
			{ RequiredAmount: 700, Type: "Price" },
			{ RequiredTrait: "WildlifeFan", Type: "Trait" },
		],
		Effects: [{ Amount: 12, Mood: "Energetic", Type: "MoodChange" }],
		FunFact: "Jackrabbits can leap over three feet in a single hop, perfect for hopping over awkward situations!",
		Name: "Jackrabbit",
		Type: "Quirkymal",
	},
	Jaguar: {
		Animation: "JaguarAnimation",
		Conditions: [
			{ RequiredAmount: 1800, Type: "Price" },
			{ RequiredTrait: "BigCatLover", Type: "Trait" },
		],
		Effects: [{ Amount: 22, Mood: "Strong", Type: "MoodChange" }],
		FunFact: "Jaguar can leap from tree to tree, but always checks the ground first for fun.",
		Name: "Jaguar",
		Type: "Quirkymal",
	},
	Javelina: {
		Animation: "JavelinaAnimation",
		Conditions: [
			{ RequiredAmount: 900, Type: "Price" },
			{ RequiredTrait: "WildlifeFan", Type: "Trait" },
		],
		Effects: [{ Amount: 14, Mood: "Stubborn", Type: "MoodChange" }],
		FunFact: "Javelina loves rolling in the mud but always takes a bath afterward.",
		Name: "Javelina",
		Type: "Quirkymal",
	},
	Jellyfish: {
		Animation: "JellyfishAnimation",
		Conditions: [
			{ RequiredAmount: 500, Type: "Price" },
			{ RequiredTrait: "AquaticFan", Type: "Trait" },
		],
		Effects: [{ Amount: 10, Mood: "Serene", Type: "MoodChange" }],
		FunFact: "Jellyfish loves drifting with the current, but always wiggles to the rhythm.",
		Name: "Jellyfish",
		Type: "Quirkymal",
	},
	Jerboa: {
		Animation: "JerboaAnimation",
		Conditions: [
			{ RequiredAmount: 800, Type: "Price" },
			{ RequiredTrait: "RodentFan", Type: "Trait" },
		],
		Effects: [{ Amount: 12, Mood: "Curious", Type: "MoodChange" }],
		FunFact: "Jerboa loves to dig tunnels but always leaves a trail of dirt behind.",
		Name: "Jerboa",
		Type: "Quirkymal",
	},
	Kakapo: {
		Animation: "KakapoAnimation",
		Conditions: [
			{ RequiredAmount: 1500, Type: "Price" },
			{ RequiredTrait: "BirdLover", Type: "Trait" },
		],
		Effects: [{ Amount: 20, Mood: "Fascinated", Type: "MoodChange" }],
		FunFact: "Kakapo loves to sleep in the day but always wakes up to see the sunset.",
		Name: "Kakapo",
		Type: "Quirkymal",
	},
	Kangaroo: {
		Animation: "KangarooAnimation",
		Conditions: [
			{ RequiredAmount: 1300, Type: "Price" },
			{ RequiredTrait: "WildlifeFan", Type: "Trait" },
		],
		Effects: [{ Amount: 18, Mood: "Energetic", Type: "MoodChange" }],
		FunFact: "Kangaroo loves hopping in zigzags for fun, always making the joey giggle.",
		Name: "Kangaroo",
		Type: "Quirkymal",
	},
	Kingfisher: {
		Animation: "KingfisherAnimation",
		Conditions: [
			{ RequiredAmount: 1000, Type: "Price" },
			{ RequiredTrait: "BirdLover", Type: "Trait" },
		],
		Effects: [{ Amount: 15, Mood: "Amazed", Type: "MoodChange" }],
		FunFact: "Kingfisher loves to fly and always lands on the tallest perch.",
		Name: "Kingfisher",
		Type: "Quirkymal",
	},
	Kirin: {
		Animation: "KirinAnimation",
		Conditions: [
			{ RequiredAmount: 3500, Type: "Price" },
			{ RequiredTrait: "MythicLover", Type: "Trait" },
		],
		Effects: [{ Amount: 30, Mood: "Awe", Type: "MoodChange" }],
		FunFact: "Kirin loves to fly and always lands on the tallest perch.",
		Name: "Kirin",
		Type: "Quirkymal",
	},
	Kitsune: {
		Animation: "KitsuneAnimation",
		Conditions: [
			{ RequiredAmount: 3200, Type: "Price" },
			{ RequiredTrait: "MythicLover", Type: "Trait" },
		],
		Effects: [{ Amount: 28, Mood: "Mysterious", Type: "MoodChange" }],
		FunFact: "Kitsune loves to play with the moon and always wiggles to the rhythm.",
		Name: "Kitsune",
		Type: "Quirkymal",
	},
	Kiwi: {
		Animation: "KiwiAnimation",
		Conditions: [
			{ RequiredAmount: 1000, Type: "Price" },
			{ RequiredTrait: "BirdLover", Type: "Trait" },
		],
		Effects: [{ Amount: 15, Mood: "Curious", Type: "MoodChange" }],
		FunFact: "Kiwi loves to sleep in the day but always wakes up to see the sunset.",
		Name: "Kiwi",
		Type: "Quirkymal",
	},
	Koala: {
		Animation: "KoalaAnimation",
		Conditions: [
			{ RequiredAmount: 1400, Type: "Price" },
			{ RequiredTrait: "WildlifeFan", Type: "Trait" },
		],
		Effects: [{ Amount: 20, Mood: "Calm", Type: "MoodChange" }],
		FunFact: "Koala loves napping for hours but always wakes up just in time for lunch.",
		Name: "Koala",
		Type: "Quirkymal",
	},
	// Koi: {
	// 	Animation: "KoiAnimation",
	// 	Conditions: [
	// 		{ RequiredAmount: 900, Type: "Price" },
	// 		{ RequiredTrait: "AquaticFan", Type: "Trait" },
	// 	],
	// 	Effects: [{ Amount: 14, Mood: "Serene", Type: "MoodChange" }],
	// 	FunFact: "Koi loves swimming in figure eights but never misses a chance to show off its colors.",
	// 	Name: "Koi",
	// 	Type: "Quirkymal",
	// },

	Kookaburra: {
		Animation: "KookaburraAnimation",
		Conditions: [
			{ RequiredAmount: 1300, Type: "Price" },
			{ RequiredTrait: "BirdLover", Type: "Trait" },
		],
		Effects: [{ Amount: 18, Mood: "Amused", Type: "MoodChange" }],
		FunFact: "Kookaburra loves to laugh and always laughs at its own jokes.",
		Name: "Kookaburra",
		Type: "Quirkymal",
	},
	Lamb: {
		Animation: "LambAnimation",
		Conditions: [
			{ RequiredAmount: 600, Type: "Price" },
			{ RequiredTrait: "FarmLover", Type: "Trait" },
		],
		Effects: [{ Amount: 12, Mood: "Nurturing", Type: "MoodChange" }],
		FunFact: "Lamb is the Fluffiest Quirkymal ever, and it knows it.",
		Name: "Lamb",
		Type: "Quirkymal",
	},
	Lemur: {
		Animation: "LemurAnimation",
		Conditions: [
			{ RequiredAmount: 1100, Type: "Price" },
			{ RequiredTrait: "PrimateLover", Type: "Trait" },
		],
		Effects: [{ Amount: 17, Mood: "Playful", Type: "MoodChange" }],
		FunFact: "Lemur loves to swing through the trees and always lands on its feet.",
		Name: "Lemur",
		Type: "Quirkymal",
	},
	Leopard: {
		Animation: "LeopardAnimation",
		Conditions: [
			{ RequiredAmount: 1800, Type: "Price" },
			{ RequiredTrait: "BigCatLover", Type: "Trait" },
		],
		Effects: [{ Amount: 22, Mood: "Stealthy", Type: "MoodChange" }],
		FunFact: "Leopard can move silently through the trees, but it always leaves a paw print behind as a signature.",
		Name: "Leopard",
		Type: "Quirkymal",
	},
	Leviathan: {
		Animation: "LeviathanAnimation",
		Conditions: [
			{ RequiredAmount: 5000, Type: "Price" },
			{ RequiredTrait: "MythicLover", Type: "Trait" },
		],
		Effects: [{ Amount: 35, Mood: "Awe", Type: "MoodChange" }],
		FunFact: "Big, scary, but secretly loves knitting seaweed scarves.",
		Name: "Leviathan",
		Type: "Quirkymal",
	},
	Lion: {
		Animation: "LionAnimation",
		Conditions: [
			{ RequiredAmount: 2000, Type: "Price" },
			{ RequiredTrait: "BigCatLover", Type: "Trait" },
		],
		Effects: [{ Amount: 25, Mood: "Majestic", Type: "MoodChange" }],
		FunFact: "Lion's roar can be heard for miles, but it only roars when it’s truly proud.",
		Name: "Lion",
		Type: "Quirkymal",
	},
	Lioness: {
		Animation: "LionessAnimation",
		Conditions: [
			{ RequiredAmount: 1800, Type: "Price" },
			{ RequiredTrait: "BigCatLover", Type: "Trait" },
		],
		Effects: [{ Amount: 22, Mood: "Confident", Type: "MoodChange" }],
		FunFact: "Lioness loves to patrol her territory and always stands tall.",
		Name: "Lioness",
		Type: "Quirkymal",
	},
	Llama: {
		Animation: "LlamaAnimation",
		Conditions: [
			{ RequiredAmount: 800, Type: "Price" },
			{ RequiredTrait: "FarmLover", Type: "Trait" },
		],
		Effects: [{ Amount: 12, Mood: "Mischievous", Type: "MoodChange" }],
		FunFact: "Llama loves to spit for fun, but it always aims for the grass.",
		Name: "Llama",
		Type: "Quirkymal",
	},
	Lobster: {
		Animation: "LobsterAnimation",
		Conditions: [
			{ RequiredAmount: 600, Type: "Price" },
			{ RequiredTrait: "AquaticFan", Type: "Trait" },
		],
		Effects: [{ Amount: 10, Mood: "Confident", Type: "MoodChange" }],
		FunFact: "Lobster loves to march sideways across the ocean floor, always leaving a trail in the sand.",
		Name: "Lobster",
		Type: "Quirkymal",
	},
	Lynx: {
		Animation: "LynxAnimation",
		Conditions: [
			{ RequiredAmount: 1500, Type: "Price" },
			{ RequiredTrait: "BigCatLover", Type: "Trait" },
		],
		Effects: [{ Amount: 18, Mood: "Mysterious", Type: "MoodChange" }],
		FunFact: "Lynx can leap across the widest gaps but prefers to watch the sunrise from a high perch.",
		Name: "Lynx",
		Type: "Quirkymal",
	},
	Macaw: {
		Animation: "MacawAnimation",
		Conditions: [
			{ RequiredAmount: 1400, Type: "Price" },
			{ RequiredTrait: "BirdLover", Type: "Trait" },
		],
		Effects: [{ Amount: 20, Mood: "Vibrant", Type: "MoodChange" }],
		FunFact: "Macaw loves mimicking the sounds of the forest, but it always adds its own twist.",
		Name: "Macaw",
		Type: "Quirkymal",
	},
	Mallard: {
		Animation: "MallardAnimation",
		Conditions: [
			{ RequiredAmount: 700, Type: "Price" },
			{ RequiredTrait: "FarmLover", Type: "Trait" },
		],
		Effects: [{ Amount: 12, Mood: "Calm", Type: "MoodChange" }],
		FunFact: "Mallard loves to swim in the pond and always waddles to see the sunset.",
		Name: "Mallard",
		Type: "Quirkymal",
	},
	Manatee: {
		Animation: "ManateeAnimation",
		Conditions: [
			{ RequiredAmount: 1600, Type: "Price" },
			{ RequiredTrait: "AquaticFan", Type: "Trait" },
		],
		Effects: [{ Amount: 22, Mood: "Tranquil", Type: "MoodChange" }],
		FunFact: "Manatee loves gliding through the water and always greets every fish it meets.",
		Name: "Manatee",
		Type: "Quirkymal",
	},
	// Mandrill: {
	// 	Animation: "MandrillAnimation",
	// 	Conditions: [
	// 		{ RequiredAmount: 1800, Type: "Price" },
	// 		{ RequiredTrait: "PrimateLover", Type: "Trait" },
	// 	],
	// 	Effects: [{ Amount: 22, Mood: "Playful", Type: "MoodChange" }],
	// 	FunFact: "Mandrill's colorful face lights up even brighter when it's excited.",
	// 	Name: "Mandrill",
	// 	Type: "Quirkymal",
	// },
	Marten: {
		Animation: "MartenAnimation",
		Conditions: [
			{ RequiredAmount: 900, Type: "Price" },
			{ RequiredTrait: "WildlifeFan", Type: "Trait" },
		],
		Effects: [{ Amount: 14, Mood: "Mischievous", Type: "MoodChange" }],
		FunFact: "Marten loves to hide in the tall grass and always leaves a trail of leaves behind.",
		Name: "Marten",
		Type: "Quirkymal",
	},
	Meerkat: {
		Animation: "MeerkatAnimation",
		Conditions: [
			{ RequiredAmount: 800, Type: "Price" },
			{ RequiredTrait: "WildlifeFan", Type: "Trait" },
		],
		Effects: [{ Amount: 12, Mood: "Curious", Type: "MoodChange" }],
		FunFact: "Meerkat loves standing tall and scanning the horizon, but it always wags its tail when excited.",
		Name: "Meerkat",
		Type: "Quirkymal",
	},
	// Mockingbird: {
	// 	Animation: "MockingbirdAnimation",
	// 	Conditions: [
	// 		{ RequiredAmount: 600, Type: "Price" },
	// 		{ RequiredTrait: "BirdLover", Type: "Trait" },
	// 	],
	// 	Effects: [{ Amount: 10, Mood: "Amused", Type: "MoodChange" }],
	// 	FunFact: "Mockingbird loves copying other birds' songs but always adds a funny twist at the end.",
	// 	Name: "Mockingbird",
	// 	Type: "Quirkymal",
	// },
	Mole: {
		Animation: "MoleAnimation",
		Conditions: [
			{ RequiredAmount: 700, Type: "Price" },
			{ RequiredTrait: "WildlifeFan", Type: "Trait" },
		],
		Effects: [{ Amount: 12, Mood: "Curious", Type: "MoodChange" }],
		FunFact: "Mole can dig tunnels faster than it can eat its breakfast.",
		Name: "Mole",
		Type: "Quirkymal",
	},
	MonitorLizard: {
		Animation: "MonitorLizardAnimation",
		Conditions: [
			{ RequiredAmount: 1400, Type: "Price" },
			{ RequiredTrait: "ReptileFan", Type: "Trait" },
		],
		Effects: [{ Amount: 18, Mood: "Fascinated", Type: "MoodChange" }],
		FunFact: "Monitor lizard loves to hide in the shadows and always looks for the next hiding spot.",
		Name: "MonitorLizard",
		Type: "Quirkymal",
	},
	Monkey: {
		Animation: "MonkeyAnimation",
		Conditions: [
			{ RequiredAmount: 1000, Type: "Price" },
			{ RequiredTrait: "PrimateLover", Type: "Trait" },
		],
		Effects: [{ Amount: 15, Mood: "Playful", Type: "MoodChange" }],
		FunFact: "Monkey loves to swing through the trees and always lands on its feet.",
		Name: "Monkey",
		Type: "Quirkymal",
	},
	Moose: {
		Animation: "MooseAnimation",
		Conditions: [
			{ RequiredAmount: 1500, Type: "Price" },
			{ RequiredTrait: "WildlifeFan", Type: "Trait" },
		],
		Effects: [{ Amount: 18, Mood: "Calm", Type: "MoodChange" }],
		FunFact: "Moose loves standing in the middle of a stream, feeling the cool water rush by.",
		Name: "Moose",
		Type: "Quirkymal",
	},
	Mouse: {
		Animation: "MouseAnimation",
		Conditions: [
			{ RequiredAmount: 500, Type: "Price" },
			{ RequiredTrait: "RodentFan", Type: "Trait" },
		],
		Effects: [{ Amount: 10, Mood: "Adorable", Type: "MoodChange" }],
		FunFact: "Mouse loves nibbling on cheese but always saves a piece for its friends.",
		Name: "Mouse",
		Type: "Quirkymal",
	},
	Mousedeer: {
		Animation: "MousedeerAnimation",
		Conditions: [
			{ RequiredAmount: 1200, Type: "Price" },
			{ RequiredTrait: "ForestLover", Type: "Trait" },
		],
		Effects: [{ Amount: 18, Mood: "Intrigued", Type: "MoodChange" }],
		FunFact: "Mousedeer loves to nibble on leaves but always leaves a trail of crumbs behind.",
		Name: "Mousedeer",
		Type: "Quirkymal",
	},
	Mudskipper: {
		Animation: "MudskipperAnimation",
		Conditions: [
			{ RequiredAmount: 700, Type: "Price" },
			{ RequiredTrait: "AquaticFan", Type: "Trait" },
		],
		Effects: [{ Amount: 12, Mood: "Curious", Type: "MoodChange" }],
		FunFact: "Mudskipper loves to swim in the mud and always leaves a trail of bubbles behind.",
		Name: "Mudskipper",
		Type: "Quirkymal",
	},
	Muskrat: {
		Animation: "MuskratAnimation",
		Conditions: [
			{ RequiredAmount: 800, Type: "Price" },
			{ RequiredTrait: "WildlifeFan", Type: "Trait" },
		],
		Effects: [{ Amount: 12, Mood: "Fascinated", Type: "MoodChange" }],
		FunFact: "A furry water architect that could outbuild Bob the Builder with its amazing lodges.",
		Name: "Muskrat",
		Type: "Quirkymal",
	},
	Narwhal: {
		Animation: "NarwhalAnimation",
		Conditions: [
			{ RequiredAmount: 1800, Type: "Price" },
			{ RequiredTrait: "AquaticFan", Type: "Trait" },
		],
		Effects: [{ Amount: 22, Mood: "Majestic", Type: "MoodChange" }],
		FunFact: "Narwhal loves showing off its tusk by carving shapes into icebergs.",
		Name: "Narwhal",
		Type: "Quirkymal",
	},
	// Newt: {
	// 	Animation: "NewtAnimation",
	// 	Conditions: [
	// 		{ RequiredAmount: 500, Type: "Price" },
	// 		{ RequiredTrait: "AmphibianFan", Type: "Trait" },
	// 	],
	// 	Effects: [{ Amount: 10, Mood: "Curious", Type: "MoodChange" }],
	// 	FunFact: "Newt loves to dart around in the water, racing fish but always letting them win.",
	// 	Name: "Newt",
	// 	Type: "Quirkymal",
	// },
	Numbat: {
		Animation: "NumbatAnimation",
		Conditions: [
			{ RequiredAmount: 1000, Type: "Price" },
			{ RequiredTrait: "WildlifeFan", Type: "Trait" },
		],
		Effects: [{ Amount: 15, Mood: "Curious", Type: "MoodChange" }],
		FunFact: "The stripy superhero of the outback, munching on termites like it's an all-you-can-eat buffet.",
		Name: "Numbat",
		Type: "Quirkymal",
	},
	// Ocelot: {
	// 	Animation: "OcelotAnimation",
	// 	Conditions: [
	// 		{ RequiredAmount: 1400, Type: "Price" },
	// 		{ RequiredTrait: "BigCatLover", Type: "Trait" },
	// 	],
	// 	Effects: [{ Amount: 20, Mood: "Stealthy", Type: "MoodChange" }],
	// 	FunFact: "Ocelot loves sneaking through the tall grass, but always stops to watch the sunset.",
	// 	Name: "Ocelot",
	// 	Type: "Quirkymal",
	// },
	Octopus: {
		Animation: "OctopusAnimation",
		Conditions: [
			{ RequiredAmount: 1600, Type: "Price" },
			{ RequiredTrait: "AquaticFan", Type: "Trait" },
		],
		Effects: [{ Amount: 22, Mood: "Clever", Type: "MoodChange" }],
		FunFact: "Octopus loves playing hide and seek but always hides in the most unexpected places.",
		Name: "Octopus",
		Type: "Quirkymal",
	},
	OrangUtan: {
		Animation: "OrangUtanAnimation",
		Conditions: [
			{ RequiredAmount: 1600, Type: "Price" },
			{ RequiredTrait: "PrimateLover", Type: "Trait" },
		],
		Effects: [{ Amount: 20, Mood: "Playful", Type: "MoodChange" }],
		FunFact: "Orangutan loves to swing through the trees and always lands on its feet.",
		Name: "OrangUtan",
		Type: "Quirkymal",
	},
	Orca: {
		Animation: "OrcaAnimation",
		Conditions: [
			{ RequiredAmount: 2500, Type: "Price" },
			{ RequiredTrait: "AquaticFan", Type: "Trait" },
		],
		Effects: [{ Amount: 28, Mood: "Powerful", Type: "MoodChange" }],
		FunFact: "Orca loves to swim in the ocean and always leaves a trail of bubbles behind.",
		Name: "Orca",
		Type: "Quirkymal",
	},
	Ostrich: {
		Animation: "OstrichAnimation",
		Conditions: [
			{ RequiredAmount: 1500, Type: "Price" },
			{ RequiredTrait: "BirdLover", Type: "Trait" },
		],
		Effects: [{ Amount: 20, Mood: "Energetic", Type: "MoodChange" }],
		FunFact: "Ostrich can run faster than anyone else, but it loves to stop and admire the view.",
		Name: "Ostrich",
		Type: "Quirkymal",
	},
	Otter: {
		Animation: "OtterAnimation",
		Conditions: [
			{ RequiredAmount: 1000, Type: "Price" },
			{ RequiredTrait: "AquaticFan", Type: "Trait" },
		],
		Effects: [{ Amount: 15, Mood: "Playful", Type: "MoodChange" }],
		FunFact: "Otter loves to play with its friends but always stops to admire the sunset.",
		Name: "Otter",
		Type: "Quirkymal",
	},
	Owl: {
		Animation: "OwlAnimation",
		Conditions: [
			{ RequiredAmount: 1400, Type: "Price" },
			{ RequiredTrait: "BirdLover", Type: "Trait" },
		],
		Effects: [{ Amount: 20, Mood: "Wise", Type: "MoodChange" }],
		FunFact: "Owl loves hooting at the moon but always turns its head to watch the stars.",
		Name: "Owl",
		Type: "Quirkymal",
	},
	Ox: {
		Animation: "OxAnimation",
		Conditions: [
			{ RequiredAmount: 1600, Type: "Price" },
			{ RequiredTrait: "FarmLover", Type: "Trait" },
		],
		Effects: [{ Amount: 20, Mood: "Strong", Type: "MoodChange" }],
		FunFact: "Strong, steady, and stubborn—this big guy is the gym bro of the animal world.",
		Name: "Ox",
		Type: "Quirkymal",
	},
	Panda: {
		Animation: "PandaAnimation",
		Conditions: [
			{ RequiredAmount: 1800, Type: "Price" },
			{ RequiredTrait: "WildlifeFan", Type: "Trait" },
		],
		Effects: [{ Amount: 22, Mood: "Gentle", Type: "MoodChange" }],
		FunFact: "The ultimate snooze master—unless there’s bamboo, then it’s an all-day snack fest.",
		Name: "Panda",
		Type: "Quirkymal",
	},
	// Panther: {
	// 	Animation: "PantherAnimation",
	// 	Conditions: [
	// 		{ RequiredAmount: 1800, Type: "Price" },
	// 		{ RequiredTrait: "BigCatLover", Type: "Trait" },
	// 	],
	// 	Effects: [{ Amount: 22, Mood: "Stealthy", Type: "MoodChange" }],
	// 	FunFact: "Panther loves prowling silently through the jungle but always leaves a paw print behind.",
	// 	Name: "Panther",
	// 	Type: "Quirkymal",
	// },
	Parrot: {
		Animation: "ParrotAnimation",
		Conditions: [
			{ RequiredAmount: 1200, Type: "Price" },
			{ RequiredTrait: "BirdLover", Type: "Trait" },
		],
		Effects: [{ Amount: 18, Mood: "Cheerful", Type: "MoodChange" }],
		FunFact: "Parrot loves mimicking the sounds of the jungle but always adds its own twist.",
		Name: "Parrot",
		Type: "Quirkymal",
	},
	Peacock: {
		Animation: "PeacockAnimation",
		Conditions: [
			{ RequiredAmount: 1600, Type: "Price" },
			{ RequiredTrait: "BirdLover", Type: "Trait" },
		],
		Effects: [{ Amount: 22, Mood: "Vibrant", Type: "MoodChange" }],
		FunFact: "Peacock loves showing off its feathers but always turns around to see if anyone's watching.",
		Name: "Peacock",
		Type: "Quirkymal",
	},
	Pegasus: {
		Animation: "PegasusAnimation",
		Conditions: [
			{ RequiredAmount: 3500, Type: "Price" },
			{ RequiredTrait: "MythicLover", Type: "Trait" },
		],
		Effects: [{ Amount: 30, Mood: "Awe", Type: "MoodChange" }],
		FunFact: "Pegasus loves to soar through the clouds but always stops to admire the view.",
		Name: "Pegasus",
		Type: "Quirkymal",
	},
	Pelican: {
		Animation: "PelicanAnimation",
		Conditions: [
			{ RequiredAmount: 900, Type: "Price" },
			{ RequiredTrait: "AquaticFan", Type: "Trait" },
		],
		Effects: [{ Amount: 14, Mood: "Entertained", Type: "MoodChange" }],
		FunFact: "Pelican loves diving for fish but always takes a moment to enjoy the splash.",
		Name: "Pelican",
		Type: "Quirkymal",
	},
	Penguin: {
		Animation: "PenguinAnimation",
		Conditions: [
			{ RequiredAmount: 1200, Type: "Price" },
			{ RequiredTrait: "AquaticFan", Type: "Trait" },
		],
		Effects: [{ Amount: 18, Mood: "Joyful", Type: "MoodChange" }],
		FunFact: "Penguin loves sliding on the ice, always racing its friends to the bottom.",
		Name: "Penguin",
		Type: "Quirkymal",
	},
	Phoenix: {
		Animation: "PhoenixAnimation",
		Conditions: [
			{ RequiredAmount: 4000, Type: "Price" },
			{ RequiredTrait: "MythicLover", Type: "Trait" },
		],
		Effects: [{ Amount: 30, Mood: "Awe", Type: "MoodChange" }],
		FunFact: "This bird always rises from the ashes, bringing the best glow-up game in the universe.",
		Name: "Phoenix",
		Type: "Quirkymal",
	},
	Pig: {
		Animation: "PigAnimation",
		Conditions: [
			{ RequiredAmount: 800, Type: "Price" },
			{ RequiredTrait: "FarmLover", Type: "Trait" },
		],
		Effects: [{ Amount: 12, Mood: "Playful", Type: "MoodChange" }],
		FunFact: "Pig loves to roll in the mud.",
		Name: "Pig",
		Type: "Quirkymal",
	},
	Pigeon: {
		Animation: "PigeonAnimation",
		Conditions: [
			{ RequiredAmount: 700, Type: "Price" },
			{ RequiredTrait: "BirdLover", Type: "Trait" },
		],
		Effects: [{ Amount: 12, Mood: "Curious", Type: "MoodChange" }],
		FunFact: "Pigeon loves cooing at the city skyline, but always comes back to the park for a snack.",
		Name: "Pigeon",
		Type: "Quirkymal",
	},
	Piranha: {
		Animation: "PiranhaAnimation",
		Conditions: [
			{ RequiredAmount: 1300, Type: "Price" },
			{ RequiredTrait: "AquaticFan", Type: "Trait" },
		],
		Effects: [{ Amount: 18, Mood: "Alert", Type: "MoodChange" }],
		FunFact: "They might have sharp teeth, but they prefer dining in schools—it’s a fishy dinner party!",
		Name: "Piranha",
		Type: "Quirkymal",
	},
	Platypus: {
		Animation: "PlatypusAnimation",
		Conditions: [
			{ RequiredAmount: 1400, Type: "Price" },
			{ RequiredTrait: "AquaticFan", Type: "Trait" },
		],
		Effects: [{ Amount: 20, Mood: "Curious", Type: "MoodChange" }],
		FunFact: "Platypus loves swimming upside down just to see the world from a different angle.",
		Name: "Platypus",
		Type: "Quirkymal",
	},
	PolarBear: {
		Animation: "PolarBearAnimation",
		Conditions: [
			{ RequiredAmount: 2200, Type: "Price" },
			{ RequiredTrait: "WildlifeFan", Type: "Trait" },
		],
		Effects: [{ Amount: 25, Mood: "Powerful", Type: "MoodChange" }],
		FunFact: "Polar Bear loves rolling in the snow but always stops to admire the northern lights.",
		Name: "PolarBear",
		Type: "Quirkymal",
	},
	Porcupine: {
		Animation: "PorcupineAnimation",
		Conditions: [
			{ RequiredAmount: 700, Type: "Price" },
			{ RequiredTrait: "RodentFan", Type: "Trait" },
		],
		Effects: [{ Amount: 12, Mood: "Defensive", Type: "MoodChange" }],
		FunFact: "Porcupine loves showing off its quills but always keeps them pointed away from its friends.",
		Name: "Porcupine",
		Type: "Quirkymal",
	},
	Possum: {
		Animation: "PossumAnimation",
		Conditions: [
			{ RequiredAmount: 900, Type: "Price" },
			{ RequiredTrait: "WildlifeFan", Type: "Trait" },
		],
		Effects: [{ Amount: 14, Mood: "Cunning", Type: "MoodChange" }],
		FunFact: "Professional drama queen, known for playing dead with an Oscar-worthy performance.",
		Name: "Possum",
		Type: "Quirkymal",
	},
	Prawn: {
		Animation: "PrawnAnimation",
		Conditions: [
			{ RequiredAmount: 700, Type: "Price" },
			{ RequiredTrait: "AquaticFan", Type: "Trait" },
		],
		Effects: [{ Amount: 12, Mood: "Curious", Type: "MoodChange" }],
		FunFact: "Tiny, but packs a punch—this little swimmer has moves that would make any chef jealous!",
		Name: "Prawn",
		Type: "Quirkymal",
	},
	Pronghorn: {
		Animation: "PronghornAnimation",
		Conditions: [
			{ RequiredAmount: 1600, Type: "Price" },
			{ RequiredTrait: "WildlifeFan", Type: "Trait" },
		],
		Effects: [{ Amount: 20, Mood: "Awe", Type: "MoodChange" }],
		FunFact: "The land’s fastest sprinter, clocking speeds that leave cheetahs in the dust.",
		Name: "Pronghorn",
		Type: "Quirkymal",
	},
	Pudu: {
		Animation: "PuduAnimation",
		Conditions: [
			{ RequiredAmount: 1300, Type: "Price" },
			{ RequiredTrait: "ForestLover", Type: "Trait" },
		],
		Effects: [{ Amount: 18, Mood: "Intrigued", Type: "MoodChange" }],
		FunFact: "Pudu loves to hide in the tall grass and always leaves a trail of leaves behind.",
		Name: "Pudu",
		Type: "Quirkymal",
	},
	Puffin: {
		Animation: "PuffinAnimation",
		Conditions: [
			{ RequiredAmount: 1200, Type: "Price" },
			{ RequiredTrait: "AquaticFan", Type: "Trait" },
		],
		Effects: [{ Amount: 18, Mood: "Amused", Type: "MoodChange" }],
		FunFact: "Puffin loves to fly in circles, but always stops to admire the view.",
		Name: "Puffin",
		Type: "Quirkymal",
	},
	// Puma: {
	// 	Animation: "PumaAnimation",
	// 	Conditions: [
	// 		{ RequiredAmount: 1500, Type: "Price" },
	// 		{ RequiredTrait: "BigCatLover", Type: "Trait" },
	// 	],
	// 	Effects: [{ Amount: 18, Mood: "Confident", Type: "MoodChange" }],
	// 	FunFact: "Puma loves leaping from rock to rock, but always stops to admire the view.",
	// 	Name: "Puma",
	// 	Type: "Quirkymal",
	// },
	Python: {
		Animation: "PythonAnimation",
		Conditions: [
			{ RequiredAmount: 1500, Type: "Price" },
			{ RequiredTrait: "ReptileFan", Type: "Trait" },
		],
		Effects: [{ Amount: 20, Mood: "Alert", Type: "MoodChange" }],
		FunFact: "A slow hug from this big noodle might take hours, but hey—it’s all in the name of love.",
		Name: "Python",
		Type: "Quirkymal",
	},
	Quail: {
		Animation: "QuailAnimation",
		Conditions: [
			{ RequiredAmount: 500, Type: "Price" },
			{ RequiredTrait: "BirdLover", Type: "Trait" },
		],
		Effects: [{ Amount: 10, Mood: "Curious", Type: "MoodChange" }],
		FunFact: "Quail loves pecking at the ground for seeds but always keeps an eye on the sky.",
		Name: "Quail",
		Type: "Quirkymal",
	},
	Quokka: {
		Animation: "QuokkaAnimation",
		Conditions: [
			{ RequiredAmount: 1000, Type: "Price" },
			{ RequiredTrait: "WildlifeFan", Type: "Trait" },
		],
		Effects: [{ Amount: 15, Mood: "Adorable", Type: "MoodChange" }],
		FunFact: "The happiest animal on earth! Every selfie is a smiley masterpiece.",
		Name: "Quokka",
		Type: "Quirkymal",
	},
	Rabbit: {
		Animation: "RabbitAnimation",
		Conditions: [
			{ RequiredAmount: 600, Type: "Price" },
			{ RequiredTrait: "WildlifeFan", Type: "Trait" },
		],
		Effects: [{ Amount: 12, Mood: "Playful", Type: "MoodChange" }],
		FunFact: "Rabbit loves hopping through fields of flowers but always stops to nibble on a tasty leaf.",
		Name: "Rabbit",
		Type: "Quirkymal",
	},
	Raccoon: {
		Animation: "RaccoonAnimation",
		Conditions: [
			{ RequiredAmount: 800, Type: "Price" },
			{ RequiredTrait: "WildlifeFan", Type: "Trait" },
		],
		Effects: [{ Amount: 14, Mood: "Mischievous", Type: "MoodChange" }],
		FunFact: "Raccoon loves sneaking into campsites for snacks but always leaves a trail of paw prints behind.",
		Name: "Raccoon",
		Type: "Quirkymal",
	},
	// Rat: {
	// 	Animation: "RatAnimation",
	// 	Conditions: [
	// 		{ RequiredAmount: 500, Type: "Price" },
	// 		{ RequiredTrait: "RodentFan", Type: "Trait" },
	// 	],
	// 	Effects: [{ Amount: 10, Mood: "Clever", Type: "MoodChange" }],
	// 	FunFact: "Rat loves scurrying through alleyways, but it always knows the quickest route to the bakery.",
	// 	Name: "Rat",
	// 	Type: "Quirkymal",
	// },
	Rattlesnake: {
		Animation: "RattlesnakeAnimation",
		Conditions: [
			{ RequiredAmount: 1200, Type: "Price" },
			{ RequiredTrait: "ReptileFan", Type: "Trait" },
		],
		Effects: [{ Amount: 18, Mood: "Alert", Type: "MoodChange" }],
		FunFact: "It’s like carrying a maraca on its tail, but instead of music, it’s a warning to back off.",
		Name: "Rattlesnake",
		Type: "Quirkymal",
	},
	// Raven: {
	// 	Animation: "RavenAnimation",
	// 	Conditions: [
	// 		{ RequiredAmount: 800, Type: "Price" },
	// 		{ RequiredTrait: "BirdLover", Type: "Trait" },
	// 	],
	// 	Effects: [{ Amount: 14, Mood: "Mysterious", Type: "MoodChange" }],
	// 	FunFact: "Raven loves perching on the tallest trees, always keeping an eye on everything below.",
	// 	Name: "Raven",
	// 	Type: "Quirkymal",
	// },
	RedPanda: {
		Animation: "RedPandaAnimation",
		Conditions: [
			{ RequiredAmount: 1000, Type: "Price" },
			{ RequiredTrait: "WildlifeFan", Type: "Trait" },
		],
		Effects: [{ Amount: 15, Mood: "Cute", Type: "MoodChange" }],
		FunFact: "Red Panda loves climbing bamboo, but it always takes a nap halfway up.",
		Name: "RedPanda",
		Type: "Quirkymal",
	},
	Reindeer: {
		Animation: "ReindeerAnimation",
		Conditions: [
			{ RequiredAmount: 1600, Type: "Price" },
			{ RequiredTrait: "WildlifeFan", Type: "Trait" },
		],
		Effects: [{ Amount: 22, Mood: "Joyful", Type: "MoodChange" }],
		FunFact: "Reindeer loves racing through the snow, but it always stops to admire the snowy mountains.",
		Name: "Reindeer",
		Type: "Quirkymal",
	},
	Rhino: {
		Animation: "RhinoAnimation",
		Conditions: [
			{ RequiredAmount: 2000, Type: "Price" },
			{ RequiredTrait: "SavannaLover", Type: "Trait" },
		],
		Effects: [{ Amount: 25, Mood: "Strong", Type: "MoodChange" }],
		FunFact: "Rhino loves charging through the plains but always slows down to graze.",
		Name: "Rhino",
		Type: "Quirkymal",
	},
	RiverDolphin: {
		Animation: "RiverDolphinAnimation",
		Conditions: [
			{ RequiredAmount: 1800, Type: "Price" },
			{ RequiredTrait: "AquaticFan", Type: "Trait" },
		],
		Effects: [{ Amount: 22, Mood: "Joyful", Type: "MoodChange" }],
		FunFact: "River Dolphin loves swimming in the river but always stops to bask in the sun first.",
		Name: "RiverDolphin",
		Type: "Quirkymal",
	},
	Rooster: {
		Animation: "RoosterAnimation",
		Conditions: [
			{ RequiredAmount: 600, Type: "Price" },
			{ RequiredTrait: "FarmLover", Type: "Trait" },
		],
		Effects: [{ Amount: 12, Mood: "Confident", Type: "MoodChange" }],
		FunFact: "Rooster loves crowing at sunrise, but it always waits for the perfect moment.",
		Name: "Rooster",
		Type: "Quirkymal",
	},
	// Salamander: {
	// 	Animation: "SalamanderAnimation",
	// 	Conditions: [
	// 		{ RequiredAmount: 500, Type: "Price" },
	// 		{ RequiredTrait: "AmphibianFan", Type: "Trait" },
	// 	],
	// 	Effects: [{ Amount: 10, Mood: "Curious", Type: "MoodChange" }],
	// 	FunFact: "Salamander loves darting around in the water but always stops to explore the rocks.",
	// 	Name: "Salamander",
	// 	Type: "Quirkymal",
	// },
	Salmon: {
		Animation: "SalmonAnimation",
		Conditions: [
			{ RequiredAmount: 600, Type: "Price" },
			{ RequiredTrait: "AquaticFan", Type: "Trait" },
		],
		Effects: [{ Amount: 12, Mood: "Determined", Type: "MoodChange" }],
		FunFact: "Salmon loves swimming upstream but always takes breaks to leap out of the water.",
		Name: "Salmon",
		Type: "Quirkymal",
	},
	Sardine: {
		Animation: "SardineAnimation",
		Conditions: [
			{ RequiredAmount: 400, Type: "Price" },
			{ RequiredTrait: "AquaticFan", Type: "Trait" },
		],
		Effects: [{ Amount: 8, Mood: "Curious", Type: "MoodChange" }],
		FunFact: "Sardine loves swimming in the ocean, but it always stops to admire the sunset.",
		Name: "Sardine",
		Type: "Quirkymal",
	},
	// Scorpion: {
	// 	Animation: "ScorpionAnimation",
	// 	Conditions: [
	// 		{ RequiredAmount: 1200, Type: "Price" },
	// 		{ RequiredTrait: "DesertLover", Type: "Trait" },
	// 	],
	// 	Effects: [{ Amount: 18, Mood: "Alert", Type: "MoodChange" }],
	// 	FunFact: "Scorpion loves to practice its tail flicks, but it never stings without reason.",
	// 	Name: "Scorpion",
	// 	Type: "Quirkymal",
	// },
	SeaHorse: {
		Animation: "SeaHorseAnimation",
		Conditions: [
			{ RequiredAmount: 1000, Type: "Price" },
			{ RequiredTrait: "AquaticFan", Type: "Trait" },
		],
		Effects: [{ Amount: 15, Mood: "Fascinated", Type: "MoodChange" }],
		FunFact: "Sea Horse loves swimming in the ocean, but it always stops to bask in the sun first.",
		Name: "SeaHorse",
		Type: "Quirkymal",
	},
	SeaLion: {
		Animation: "SeaLionAnimation",
		Conditions: [
			{ RequiredAmount: 1600, Type: "Price" },
			{ RequiredTrait: "AquaticFan", Type: "Trait" },
		],
		Effects: [{ Amount: 20, Mood: "Playful", Type: "MoodChange" }],
		FunFact: "Sea Lion loves playing in the ocean, but it always stops to bask in the sun first.",
		Name: "SeaLion",
		Type: "Quirkymal",
	},
	SeaOtter: {
		Animation: "SeaOtterAnimation",
		Conditions: [
			{ RequiredAmount: 1200, Type: "Price" },
			{ RequiredTrait: "AquaticFan", Type: "Trait" },
		],
		Effects: [{ Amount: 18, Mood: "Playful", Type: "MoodChange" }],
		FunFact: "Sea Otter loves swimming in the ocean, but it always stops to bask in the sun first.",
		Name: "SeaOtter",
		Type: "Quirkymal",
	},
	Seagull: {
		Animation: "SeagullAnimation",
		Conditions: [
			{ RequiredAmount: 700, Type: "Price" },
			{ RequiredTrait: "BirdLover", Type: "Trait" },
		],
		Effects: [{ Amount: 12, Mood: "Curious", Type: "MoodChange" }],
		FunFact: "Seagull loves flying in the sky, but it always stops to admire the ocean below.",
		Name: "Seagull",
		Type: "Quirkymal",
	},
	// Seal: {
	// 	Animation: "SealAnimation",
	// 	Conditions: [
	// 		{ RequiredAmount: 1200, Type: "Price" },
	// 		{ RequiredTrait: "AquaticFan", Type: "Trait" },
	// 	],
	// 	Effects: [{ Amount: 18, Mood: "Playful", Type: "MoodChange" }],
	// 	FunFact: "Seal loves sliding into the water, but it always pauses to bask in the sun first.",
	// 	Name: "Seal",
	// 	Type: "Quirkymal",
	// },
	Serval: {
		Animation: "ServalAnimation",
		Conditions: [
			{ RequiredAmount: 1800, Type: "Price" },
			{ RequiredTrait: "BigCatLover", Type: "Trait" },
		],
		Effects: [{ Amount: 22, Mood: "Graceful", Type: "MoodChange" }],
		FunFact: "Serval loves stalking through the jungle, but it always pauses to watch the sunset.",
		Name: "Serval",
		Type: "Quirkymal",
	},
	// Shark: {
	// 	Animation: "SharkAnimation",
	// 	Conditions: [
	// 		{ RequiredAmount: 1500, Type: "Price" },
	// 		{ RequiredTrait: "AquaticFan", Type: "Trait" },
	// 	],
	// 	Effects: [{ Amount: 20, Mood: "Confident", Type: "MoodChange" }],
	// 	FunFact: "Shark loves gliding through the ocean, but it always circles its prey with a grin.",
	// 	Name: "Shark",
	// 	Type: "Quirkymal",
	// },
	Sheep: {
		Animation: "SheepAnimation",
		Conditions: [
			{ RequiredAmount: 800, Type: "Price" },
			{ RequiredTrait: "FarmLover", Type: "Trait" },
		],
		Effects: [{ Amount: 12, Mood: "Peaceful", Type: "MoodChange" }],
		FunFact: "Sheep loves grazing on fresh grass, but it always dozes off in the shade afterward.",
		Name: "Sheep",
		Type: "Quirkymal",
	},
	Shoebill: {
		Animation: "ShoebillAnimation",
		Conditions: [
			{ RequiredAmount: 1200, Type: "Price" },
			{ RequiredTrait: "BirdLover", Type: "Trait" },
		],
		Effects: [{ Amount: 18, Mood: "Intrigued", Type: "MoodChange" }],
		FunFact: "Shoebill loves to fly in the sky, but it always stops to admire the ocean below.",
		Name: "Shoebill",
		Type: "Quirkymal",
	},
	Skunk: {
		Animation: "SkunkAnimation",
		Conditions: [
			{ RequiredAmount: 700, Type: "Price" },
			{ RequiredTrait: "WildlifeFan", Type: "Trait" },
		],
		Effects: [{ Amount: 12, Mood: "Mischievous", Type: "MoodChange" }],
		FunFact: "Skunk loves spraying its scent but only does it when it’s absolutely necessary.",
		Name: "Skunk",
		Type: "Quirkymal",
	},
	Sloth: {
		Animation: "SlothAnimation",
		Conditions: [
			{ RequiredAmount: 1000, Type: "Price" },
			{ RequiredTrait: "WildlifeFan", Type: "Trait" },
		],
		Effects: [{ Amount: 15, Mood: "Relaxed", Type: "MoodChange" }],
		FunFact: "Sloth loves hanging from trees but always takes a nap in the sun.",
		Name: "Sloth",
		Type: "Quirkymal",
	},
	Snake: {
		Animation: "SnakeAnimation",
		Conditions: [
			{ RequiredAmount: 700, Type: "Price" },
			{ RequiredTrait: "ReptileFan", Type: "Trait" },
		],
		Effects: [{ Amount: 12, Mood: "Sly", Type: "MoodChange" }],
		FunFact: "Snake loves slithering through the grass but always coils up in the shade.",
		Name: "Snake",
		Type: "Quirkymal",
	},
	SnappingTurtle: {
		Animation: "SnappingTurtleAnimation",
		Conditions: [
			{ RequiredAmount: 1400, Type: "Price" },
			{ RequiredTrait: "ReptileFan", Type: "Trait" },
		],
		Effects: [{ Amount: 20, Mood: "Fascinated", Type: "MoodChange" }],
		FunFact: "Snapping Turtle loves hiding in the water but always pops up for a quick bite.",
		Name: "SnappingTurtle",
		Type: "Quirkymal",
	},
	SnowLeopard: {
		Animation: "SnowLeopardAnimation",
		Conditions: [
			{ RequiredAmount: 2000, Type: "Price" },
			{ RequiredTrait: "BigCatLover", Type: "Trait" },
		],
		Effects: [{ Amount: 25, Mood: "Majestic", Type: "MoodChange" }],
		FunFact: "Snow Leopard loves prowling through the snowy mountains, but it always stops to watch the sunrise.",
		Name: "SnowLeopard",
		Type: "Quirkymal",
	},
	SnowOwl: {
		Animation: "SnowOwlAnimation",
		Conditions: [
			{ RequiredAmount: 1500, Type: "Price" },
			{ RequiredTrait: "BirdLover", Type: "Trait" },
		],
		Effects: [{ Amount: 20, Mood: "Mysterious", Type: "MoodChange" }],
		FunFact: "Snow Owl loves flying in the sky, but it always stops to admire the snowy mountains below.",
		Name: "SnowOwl",
		Type: "Quirkymal",
	},
	SnowWeasel: {
		Animation: "SnowWeaselAnimation",
		Conditions: [
			{ RequiredAmount: 1100, Type: "Price" },
			{ RequiredTrait: "WildlifeFan", Type: "Trait" },
		],
		Effects: [{ Amount: 17, Mood: "Curious", Type: "MoodChange" }],
		FunFact: "Snow Weasel loves prowling through the snowy mountains, but it always stops to admire the view.",
		Name: "SnowWeasel",
		Type: "Quirkymal",
	},
	Sparrow: {
		Animation: "SparrowAnimation",
		Conditions: [
			{ RequiredAmount: 500, Type: "Price" },
			{ RequiredTrait: "BirdLover", Type: "Trait" },
		],
		Effects: [{ Amount: 10, Mood: "Content", Type: "MoodChange" }],
		FunFact: "Sparrow loves chirping in the sky, but it always stops to admire the ocean below.",
		Name: "Sparrow",
		Type: "Quirkymal",
	},
	// Spider: {
	// 	Animation: "SpiderAnimation",
	// 	Conditions: [
	// 		{ RequiredAmount: 500, Type: "Price" },
	// 		{ RequiredTrait: "InsectFan", Type: "Trait" },
	// 	],
	// 	Effects: [{ Amount: 10, Mood: "Curious", Type: "MoodChange" }],
	// 	FunFact: "Spider loves spinning webs in the most intricate patterns but always leaves a space for flies.",
	// 	Name: "Spider",
	// 	Type: "Quirkymal",
	// },
	Squid: {
		Animation: "SquidAnimation",
		Conditions: [
			{ RequiredAmount: 1200, Type: "Price" },
			{ RequiredTrait: "AquaticFan", Type: "Trait" },
		],
		Effects: [{ Amount: 18, Mood: "Intrigued", Type: "MoodChange" }],
		FunFact: "Squid loves swimming in the ocean, but it always stops to admire the sunset first.",
		Name: "Squid",
		Type: "Quirkymal",
	},
	Squirrel: {
		Animation: "SquirrelAnimation",
		Conditions: [
			{ RequiredAmount: 700, Type: "Price" },
			{ RequiredTrait: "WildlifeFan", Type: "Trait" },
		],
		Effects: [{ Amount: 12, Mood: "Cheerful", Type: "MoodChange" }],
		FunFact: "Squirrel loves gathering acorns but always forgets where it hid them.",
		Name: "Squirrel",
		Type: "Quirkymal",
	},
	// Starling: {
	// 	Animation: "StarlingAnimation",
	// 	Conditions: [
	// 		{ RequiredAmount: 500, Type: "Price" },
	// 		{ RequiredTrait: "BirdLover", Type: "Trait" },
	// 	],
	// 	Effects: [{ Amount: 10, Mood: "Playful", Type: "MoodChange" }],
	// 	FunFact: "Starling loves mimicking other birds' songs but always adds a funny twist at the end.",
	// 	Name: "Starling",
	// 	Type: "Quirkymal",
	// },
	Swan: {
		Animation: "SwanAnimation",
		Conditions: [
			{ RequiredAmount: 1200, Type: "Price" },
			{ RequiredTrait: "BirdLover", Type: "Trait" },
		],
		Effects: [{ Amount: 18, Mood: "Graceful", Type: "MoodChange" }],
		FunFact: "Swan loves gliding across the water, but it always flaps its wings when excited.",
		Name: "Swan",
		Type: "Quirkymal",
	},
	Taipan: {
		Animation: "TaipanAnimation",
		Conditions: [
			{ RequiredAmount: 1800, Type: "Price" },
			{ RequiredTrait: "ReptileFan", Type: "Trait" },
		],
		Effects: [{ Amount: 22, Mood: "Alert", Type: "MoodChange" }],
		FunFact: "Taipan loves striking at its prey but always hides in the shadows.",
		Name: "Taipan",
		Type: "Quirkymal",
	},
	Tapir: {
		Animation: "TapirAnimation",
		Conditions: [
			{ RequiredAmount: 1400, Type: "Price" },
			{ RequiredTrait: "WildlifeFan", Type: "Trait" },
		],
		Effects: [{ Amount: 18, Mood: "Curious", Type: "MoodChange" }],
		FunFact: "Tapir loves grazing on the savannah but always takes a break to enjoy the view.",
		Name: "Tapir",
		Type: "Quirkymal",
	},
	TasmanianDevil: {
		Animation: "TasmanianDevilAnimation",
		Conditions: [
			{ RequiredAmount: 1600, Type: "Price" },
			{ RequiredTrait: "WildlifeFan", Type: "Trait" },
		],
		Effects: [{ Amount: 20, Mood: "Mischievous", Type: "MoodChange" }],
		FunFact: "Tasmanian Devil loves playing with its prey but always hides in the shadows.",
		Name: "TasmanianDevil",
		Type: "Quirkymal",
	},
	Tiger: {
		Animation: "TigerAnimation",
		Conditions: [
			{ RequiredAmount: 2000, Type: "Price" },
			{ RequiredTrait: "BigCatLover", Type: "Trait" },
		],
		Effects: [{ Amount: 25, Mood: "Powerful", Type: "MoodChange" }],
		FunFact: "Tiger loves stalking through the jungle, but it always pauses to admire the moonlight.",
		Name: "Tiger",
		Type: "Quirkymal",
	},
	Tortoise: {
		Animation: "TortoiseAnimation",
		Conditions: [
			{ RequiredAmount: 900, Type: "Price" },
			{ RequiredTrait: "ReptileFan", Type: "Trait" },
		],
		Effects: [{ Amount: 14, Mood: "Calm", Type: "MoodChange" }],
		FunFact: "Tortoise loves taking its time, but it always gets where it needs to be.",
		Name: "Tortoise",
		Type: "Quirkymal",
	},
	Toucan: {
		Animation: "ToucanAnimation",
		Conditions: [
			{ RequiredAmount: 1400, Type: "Price" },
			{ RequiredTrait: "BirdLover", Type: "Trait" },
		],
		Effects: [{ Amount: 20, Mood: "Cheerful", Type: "MoodChange" }],
		FunFact: "Toucan loves to show off its colorful beak, but it always pecks at fruit for a snack.",
		Name: "Toucan",
		Type: "Quirkymal",
	},
	// Trout: {
	// 	Animation: "TroutAnimation",
	// 	Conditions: [
	// 		{ RequiredAmount: 500, Type: "Price" },
	// 		{ RequiredTrait: "AquaticFan", Type: "Trait" },
	// 	],
	// 	Effects: [{ Amount: 10, Mood: "Relaxed", Type: "MoodChange" }],
	// 	FunFact: "Trout loves swimming in the cool river but always leaps out for a quick splash.",
	// 	Name: "Trout",
	// 	Type: "Quirkymal",
	// },
	Tuna: {
		Animation: "TunaAnimation",
		Conditions: [
			{ RequiredAmount: 600, Type: "Price" },
			{ RequiredTrait: "AquaticFan", Type: "Trait" },
		],
		Effects: [{ Amount: 12, Mood: "Energetic", Type: "MoodChange" }],
		FunFact: "Tuna loves swimming at full speed but always slows down to enjoy the view.",
		Name: "Tuna",
		Type: "Quirkymal",
	},
	Turkey: {
		Animation: "TurkeyAnimation",
		Conditions: [
			{ RequiredAmount: 800, Type: "Price" },
			{ RequiredTrait: "FarmLover", Type: "Trait" },
		],
		Effects: [{ Amount: 12, Mood: "Amused", Type: "MoodChange" }],
		FunFact: "Turkey loves clucking in the barnyard but always pecks at the ground for a snack.",
		Name: "Turkey",
		Type: "Quirkymal",
	},
	Turtle: {
		Animation: "TurtleAnimation",
		Conditions: [
			{ RequiredAmount: 700, Type: "Price" },
			{ RequiredTrait: "ReptileFan", Type: "Trait" },
		],
		Effects: [{ Amount: 12, Mood: "Relaxed", Type: "MoodChange" }],
		FunFact: "Turtle loves basking in the sun but always dives into the water for a quick swim.",
		Name: "Turtle",
		Type: "Quirkymal",
	},
	Vulture: {
		Animation: "VultureAnimation",
		Conditions: [
			{ RequiredAmount: 900, Type: "Price" },
			{ RequiredTrait: "BirdLover", Type: "Trait" },
		],
		Effects: [{ Amount: 14, Mood: "Mysterious", Type: "MoodChange" }],
		FunFact: "Vulture loves circling high in the sky, but it always swoops down for a closer look.",
		Name: "Vulture",
		Type: "Quirkymal",
	},
	Walrus: {
		Animation: "WalrusAnimation",
		Conditions: [
			{ RequiredAmount: 1800, Type: "Price" },
			{ RequiredTrait: "AquaticFan", Type: "Trait" },
		],
		Effects: [{ Amount: 22, Mood: "Strong", Type: "MoodChange" }],
		FunFact: "Walrus loves lounging on the ice, but it always slides into the water for a swim.",
		Name: "Walrus",
		Type: "Quirkymal",
	},
	// Weasel: {
	// 	Animation: "WeaselAnimation",
	// 	Conditions: [
	// 		{ RequiredAmount: 600, Type: "Price" },
	// 		{ RequiredTrait: "RodentFan", Type: "Trait" },
	// 	],
	// 	Effects: [{ Amount: 10, Mood: "Mischievous", Type: "MoodChange" }],
	// 	FunFact: "Weasel loves sneaking through the grass but always stops to watch the sunset.",
	// 	Name: "Weasel",
	// 	Type: "Quirkymal",
	// },
	Whale: {
		Animation: "WhaleAnimation",
		Conditions: [
			{ RequiredAmount: 2200, Type: "Price" },
			{ RequiredTrait: "AquaticFan", Type: "Trait" },
		],
		Effects: [{ Amount: 25, Mood: "Majestic", Type: "MoodChange" }],
		FunFact: "Whale loves singing the songs of the sea but always breaches the surface to watch the stars.",
		Name: "Whale",
		Type: "Quirkymal",
	},
	// Wildcat: {
	// 	Animation: "WildcatAnimation",
	// 	Conditions: [
	// 		{ RequiredAmount: 1600, Type: "Price" },
	// 		{ RequiredTrait: "BigCatLover", Type: "Trait" },
	// 	],
	// 	Effects: [{ Amount: 20, Mood: "Stealthy", Type: "MoodChange" }],
	// 	FunFact: "Wildcat loves prowling through the forest, but it always stops to sharpen its claws on a tree.",
	// 	Name: "Wildcat",
	// 	Type: "Quirkymal",
	// },
	Wildebeest: {
		Animation: "WildebeestAnimation",
		Conditions: [
			{ RequiredAmount: 1800, Type: "Price" },
			{ RequiredTrait: "SavannaLover", Type: "Trait" },
		],
		Effects: [{ Amount: 22, Mood: "Strong", Type: "MoodChange" }],
		FunFact: "Wildebeest loves galloping across the plains, but it always stops to admire the sunset.",
		Name: "Wildebeest",
		Type: "Quirkymal",
	},
	Wolf: {
		Animation: "WolfAnimation",
		Conditions: [
			{ RequiredAmount: 1800, Type: "Price" },
			{ RequiredTrait: "WildlifeFan", Type: "Trait" },
		],
		Effects: [{ Amount: 22, Mood: "Powerful", Type: "MoodChange" }],
		FunFact: "Wolf loves howling at the moon but always joins its pack for a run afterward.",
		Name: "Wolf",
		Type: "Quirkymal",
	},
	// Wolverine: {
	// 	Animation: "WolverineAnimation",
	// 	Conditions: [
	// 		{ RequiredAmount: 1400, Type: "Price" },
	// 		{ RequiredTrait: "WildlifeFan", Type: "Trait" },
	// 	],
	// 	Effects: [{ Amount: 20, Mood: "Fierce", Type: "MoodChange" }],
	// 	FunFact: "Wolverine loves prowling through the snowy forest, but it always stops to admire the view.",
	// 	Name: "Wolverine",
	// 	Type: "Quirkymal",
	// },
	Wombat: {
		Animation: "WombatAnimation",
		Conditions: [
			{ RequiredAmount: 700, Type: "Price" },
			{ RequiredTrait: "WildlifeFan", Type: "Trait" },
		],
		Effects: [{ Amount: 12, Mood: "Relaxed", Type: "MoodChange" }],
		FunFact: "Wombat loves burrowing through the earth but always stops to admire the wildflowers.",
		Name: "Wombat",
		Type: "Quirkymal",
	},
	// Woodpecker: {
	// 	Animation: "WoodpeckerAnimation",
	// 	Conditions: [
	// 		{ RequiredAmount: 800, Type: "Price" },
	// 		{ RequiredTrait: "BirdLover", Type: "Trait" },
	// 	],
	// 	Effects: [{ Amount: 14, Mood: "Focused", Type: "MoodChange" }],
	// 	FunFact: "Woodpecker loves tapping away at the trees, but it always pauses to listen for echoes.",
	// 	Name: "Woodpecker",
	// 	Type: "Quirkymal",
	// },
	Wyvern: {
		Animation: "WyvernAnimation",
		Conditions: [
			{ RequiredAmount: 4000, Type: "Price" },
			{ RequiredTrait: "MythicLover", Type: "Trait" },
		],
		Effects: [{ Amount: 30, Mood: "Powerful", Type: "MoodChange" }],
		FunFact: "Wyvern loves soaring through the sky, but it always dives down for a closer look.",
		Name: "Wyvern",
		Type: "Quirkymal",
	},
	// Yak: {
	// 	Animation: "YakAnimation",
	// 	Conditions: [
	// 		{ RequiredAmount: 1400, Type: "Price" },
	// 		{ RequiredTrait: "WildlifeFan", Type: "Trait" },
	// 	],
	// 	Effects: [{ Amount: 18, Mood: "Strong", Type: "MoodChange" }],
	// 	FunFact: "Yak loves grazing on the mountainside, but it always takes a break to enjoy the view.",
	// 	Name: "Yak",
	// 	Type: "Quirkymal",
	// },
	Zebra: {
		Animation: "ZebraAnimation",
		Conditions: [
			{ RequiredAmount: 1800, Type: "Price" },
			{ RequiredTrait: "SavannaLover", Type: "Trait" },
		],
		Effects: [{ Amount: 22, Mood: "Energetic", Type: "MoodChange" }],
		FunFact: "Zebra loves galloping across the plains, but it always stops to admire its stripes.",
		Name: "Zebra",
		Type: "Quirkymal",
	},
};
